version: "3.8"
services:
  minio:
    image: minio/minio:latest
    container_name: export_minio_cloud
    ports:
      - "9000:9000" # cong API de upload/download file
      - "9001:9001" # cong giao dien web console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: export_rabbitmq
    ports:
      - "5672:5672" # cong de ket noi va gui/nhan message
      - "15672:15672" # cong de truy cap web management console
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
