# application.properties (File này push lên GitHub)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

auth.jwt.secret=${JWT_SECRET_KEY}
auth.jwt.expiration=${JWT_EXPIRATION}
uth.app.jwtRefreshExpirationMs=${JWT_REFRESH_EXPIRATION}

# Các cấu hình khác giữ nguyên
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect