package uth.edu.report.service.impl;

import uth.edu.report.Exception.ResourceNotFoundException;
import uth.edu.report.dto.ReportRequestDTO;
import uth.edu.report.dto.ReportResponseDTO;
import uth.edu.report.mapper.ReportMapper;
import uth.edu.report.model.Report;
import uth.edu.report.repository.ReportRepository;
import uth.edu.report.service.ReportService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class ReportServiceImpl implements ReportService {

    private final ReportRepository reportRepository;
    private final ReportMapper reportMapper;

    @Override
    @Transactional
    public ReportResponseDTO createReport(ReportRequestDTO requestDTO) {
        log.info("Creating report for groupId={}, generatedBy={}",
                requestDTO.getGroupId(), requestDTO.getGeneratedBy());

        Report report = reportMapper.toEntity(requestDTO);
        Report saved = reportRepository.save(report);

        log.info("Report created with id={}", saved.getReportId());
        return reportMapper.toDTO(saved);
    }

    @Override
    @Transactional(readOnly = true)
    public ReportResponseDTO getReportById(UUID reportId) {
        log.info("Fetching report id={}", reportId);

        Report report = reportRepository.findById(reportId)
                .orElseThrow(() -> new ResourceNotFoundException("Report not found with id: " + reportId));

        return reportMapper.toDTO(report);
    }

    @Override
    @Transactional(readOnly = true)
    public List<ReportResponseDTO> getAllReports() {
        log.info("Fetching all reports");

        return reportRepository.findAll()
                .stream()
                .map(reportMapper::toDTO)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<ReportResponseDTO> getReportsByGroup(UUID groupId) {
        log.info("Fetching reports for groupId={}", groupId);

        return reportRepository.findByGroupId(groupId)
                .stream()
                .map(reportMapper::toDTO)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<ReportResponseDTO> getReportsByGeneratedBy(UUID userId) {
        log.info("Fetching reports generated by userId={}", userId);

        return reportRepository.findByGeneratedBy(userId)
                .stream()
                .map(reportMapper::toDTO)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<ReportResponseDTO> getReportsByType(String reportType) {
        log.info("Fetching reports of type={}", reportType);

        return reportRepository.findByReportType(reportType)
                .stream()
                .map(reportMapper::toDTO)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public ReportResponseDTO updateReport(UUID reportId, ReportRequestDTO requestDTO) {
        log.info("Updating report id={}", reportId);

        Report existing = reportRepository.findById(reportId)
                .orElseThrow(() ->
                    new ResourceNotFoundException("Report not found with id: " + reportId));

        existing.setGroupId(requestDTO.getGroupId());
        existing.setReportIdUser(requestDTO.getReportIdUser());
        existing.setTitle(requestDTO.getTitle());
        existing.setReportType(requestDTO.getReportType());
        existing.setGeneratedBy(requestDTO.getGeneratedBy());

        Report updated = reportRepository.save(existing);
        log.info("Report updated id={}", updated.getReportId());

        return reportMapper.toDTO(updated);
    }

    @Override
    @Transactional
    public void deleteReport(UUID reportId) {
        log.info("Deleting report id={}", reportId);

        Report existing = reportRepository.findById(reportId)
                .orElseThrow(() ->
                    new ResourceNotFoundException("Report not found with id: " + reportId));

        reportRepository.delete(existing);
        log.info("Report deleted id={}", reportId);
    }
}