version: '3.8'
services:
  # Database cho Auth Service
  auth-db:
    image: postgres:15
    container_name: auth-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # Auth Service
  auth-service:
    build: 
      context: ./auth-service/auth # Thư mục chứa Dockerfile
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always # Thêm dòng này
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS:-postgres}
      JWT_SECRET_KEY: ${JWT_SECRET:-dev-secret-change-me}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  auth_db_data: