logging.level.uth.edu.task.client=DEBUG


spring.application.name=task-service
server.port=${SERVER_PORT:8084}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
#spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES}

# JWT
jwt.secret=${JWT_SECRET_KEY:${JWT_SECRET:dev-secret-change-me}}