spring.application.name=requirement-service
server.port=8083

# URL kết nối: localhost:5432 và tên database bạn đã tạo
spring.datasource.url=jdbc:postgresql://localhost:5432/requirement
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: Tự động tạo bảng dựa trên Model đã xây
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true