package com.example.report.dto;

import com.example.report.model.ReportType;
import com.example.report.model.GeneratedBy;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import java.util.UUID;

@Data
public class ReportRequest {
    
    @NotNull(message = "Group ID is required")
    private UUID groupId;
    
    @NotNull(message = "User ID is required")
    private UUID userId;
    
    @NotNull(message = "Report type is required")
    private ReportType reportType;
    
    @NotNull(message = "Generated by is required")
    private GeneratedBy generatedBy;
}